language: android

git:
  depth: 1

env:
  global:
    # General information:
    - ANDROID_TARGET=23
    - BUILD_TOOLS_VERSION=23.0.0
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)

    ##### Client project env #####

    - ANDROID_DIR=client
    - ANDROID_PROJECT_NAME=ChatApp

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_TARGET

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

before_install:
  - chmod -R ugo+x travis-script/
  - source ./travis-script/install-dependencies.sh

script:
  # Run client test
  - ./travis-script/run-client-test.sh
  # Run server test
  - ./travis-script/run-server-test.sh
